version: '3.8'

services:

  postgres:
    image: postgres:latest
    container_name: indexer
    hostname: postgres
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=indexer
    volumes:
      - ./data/pg:/var/lib/postgresql/data